apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-service
  labels:
    app: {{ .Values.app_name }}
spec:
  ports:
  - protocol: {{ .Values.protocol }}
    port: {{ .Values.service_port }}
    targetPort: {{ .Values.container_port }}
  selector:
    app: {{ .Values.app_name }}